/**
 * @file Euler3D_SWBLI.cpp
 * @brief Flat-plate shock-wave / boundary-layer interaction mesh and RH state.
 *
 * Bottom wall is no-slip. An incident oblique shock is generated by imposing
 * the Rankine–Hugoniot post-shock state on ymax for x >= Shock_X_Top.
 */
#include "Euler3D.hpp"

#include <algorithm>
#include <cmath>
#include <iostream>
#include <vector>

namespace euler3d
{
namespace
{

inline int nid(int i, int j, int k, int npx, int npy)
{
    return i + j * npx + k * npx * npy;
}

inline int cid(int i, int j, int k, int nx, int ny)
{
    return i + j * nx + k * nx * ny;
}

double theta_beta_M_residual(double beta, double M, double gamma, double theta)
{
    const double sb2 = std::sin(beta) * std::sin(beta);
    const double num = 2.0 * (1.0 / std::tan(beta)) * (M * M * sb2 - 1.0);
    const double den = M * M * (gamma + std::cos(2.0 * beta)) + 2.0;
    return std::atan(num / den) - theta;
}

double solve_shock_angle(double M, double gamma, double theta)
{
    const double mu = std::asin(std::min(1.0, 1.0 / std::max(M, 1.01)));
    double lo = mu + 1.0e-6;
    double hi = 0.5 * 3.141592653589793 - 1.0e-4;
    for (int n = 0; n < 80; ++n)
    {
        const double mid = 0.5 * (lo + hi);
        const double fm = theta_beta_M_residual(mid, M, gamma, theta);
        if (theta_beta_M_residual(lo, M, gamma, theta) * fm <= 0.0)
            hi = mid;
        else
            lo = mid;
    }
    return 0.5 * (lo + hi);
}

} // namespace

void fill_oblique_postshock(Config &cfg)
{
    const double rho1 = std::max(cfg.freestream_rho, 1.0e-14);
    const double p1 = std::max(cfg.freestream_p, 1.0e-14);
    const double a1 = std::sqrt(kGamma * p1 / rho1);
    const double M1 = std::fabs(cfg.freestream_u) / std::max(a1, 1.0e-14);
    const double theta = cfg.shock_theta_deg * 3.141592653589793 / 180.0;

    cfg.post_rho = rho1;
    cfg.post_u = cfg.freestream_u;
    cfg.post_v = cfg.freestream_v;
    cfg.post_w = cfg.freestream_w;
    cfg.post_p = p1;
    if (theta < 1.0e-8 || M1 <= 1.01)
        return;

    const double beta = solve_shock_angle(M1, kGamma, theta);
    const double Mn1 = M1 * std::sin(beta);
    const double p2 = p1 * (1.0 + 2.0 * kGamma / (kGamma + 1.0) * (Mn1 * Mn1 - 1.0));
    const double rho2 = rho1 * ((kGamma + 1.0) * Mn1 * Mn1) /
                        ((kGamma - 1.0) * Mn1 * Mn1 + 2.0);
    const double Mn2 = std::sqrt((1.0 + 0.5 * (kGamma - 1.0) * Mn1 * Mn1) /
                                 (kGamma * Mn1 * Mn1 - 0.5 * (kGamma - 1.0)));
    const double M2 = Mn2 / std::sin(std::max(beta - theta, 1.0e-8));
    const double a2 = std::sqrt(kGamma * p2 / rho2);
    const double V2 = M2 * a2;
    /* Shock from the top wall: flow is turned downward. */
    cfg.post_rho = rho2;
    cfg.post_p = p2;
    cfg.post_u = V2 * std::cos(theta);
    cfg.post_v = -V2 * std::sin(theta);
    cfg.post_w = 0.0;

    const double x_hit = cfg.shock_x_top + cfg.Ly / std::tan(beta);
    std::cout << "SWBLI RH: M1=" << M1 << " theta=" << cfg.shock_theta_deg
              << " deg  beta=" << beta * 180.0 / 3.141592653589793
              << " deg  impinge x≈" << x_hit << "  p2/p1=" << p2 / p1 << "\n";
}

Mesh make_swbli_plate_mesh(const Config &cfg)
{
    Mesh m;
    m.nx = cfg.nx;
    m.ny = cfg.ny;
    m.nz = cfg.nz;
    m.Lx = cfg.Lx;
    m.Ly = cfg.Ly;
    m.Lz = cfg.Lz;
    m.n_cells = m.nx * m.ny * m.nz;
    m.dx = cfg.Lx / std::max(m.nx, 1);
    m.dz = cfg.Lz / std::max(m.nz, 1);
    m.dy = cfg.Ly / std::max(m.ny, 1);
    m.has_nodes = true;

    const int npx = m.nx + 1, npy = m.ny + 1, npz = m.nz + 1;
    m.nodes.assign(static_cast<std::size_t>(npx) * npy * npz * 3, 0.0);

    const double stretch = std::max(cfg.y_stretch, 1.0);
    std::vector<double> ynode(static_cast<std::size_t>(npy), 0.0);
    if (stretch <= 1.0 + 1.0e-12)
    {
        for (int j = 0; j < npy; ++j)
            ynode[j] = cfg.Ly * j / m.ny;
    }
    else
    {
        const double denom = std::pow(stretch, m.ny) - 1.0;
        for (int j = 0; j < npy; ++j)
            ynode[j] = cfg.Ly * (std::pow(stretch, j) - 1.0) / denom;
    }

    for (int k = 0; k < npz; ++k)
        for (int j = 0; j < npy; ++j)
            for (int i = 0; i < npx; ++i)
            {
                const int id = nid(i, j, k, npx, npy);
                m.nodes[id * 3 + 0] = cfg.Lx * i / m.nx;
                m.nodes[id * 3 + 1] = ynode[j];
                m.nodes[id * 3 + 2] = cfg.Lz * k / m.nz;
            }

    m.xc.resize(m.n_cells);
    m.yc.resize(m.n_cells);
    m.zc.resize(m.n_cells);
    m.volume.assign(m.n_cells, 0.0);
    m.neigh.assign(m.n_cells * kFaces, -1);
    m.nxyz.assign(m.n_cells * kFaces * 3, 0.0);
    m.area.assign(m.n_cells * kFaces, 0.0);
    m.wall_face.assign(m.n_cells * kFaces, 0);
    m.bc_type.assign(m.n_cells * kFaces, BC_INTERIOR);

    auto parse_local = [](const std::string &s) {
        if (s == "noslip" || s == "no_slip" || s == "wall_viscous")
            return BC_NOSLIP;
        if (s == "extrapolate" || s == "outlet" || s == "outflow")
            return BC_EXTRAP;
        if (s == "freestream" || s == "inlet" || s == "farfield")
            return BC_FREESTREAM;
        if (s == "postshock" || s == "shock" || s == "rh")
            return BC_POSTSHOCK;
        return BC_SLIP;
    };
    const int bc_face[kFaces] = {
        parse_local(cfg.bc_xmin), parse_local(cfg.bc_xmax), parse_local(cfg.bc_ymin),
        parse_local(cfg.bc_ymax), parse_local(cfg.bc_zmin), parse_local(cfg.bc_zmax)};

    const double nrm[kFaces][3] = {{-1, 0, 0}, {1, 0, 0}, {0, -1, 0},
                                   {0, 1, 0},  {0, 0, -1}, {0, 0, 1}};

    for (int k = 0; k < m.nz; ++k)
        for (int j = 0; j < m.ny; ++j)
            for (int i = 0; i < m.nx; ++i)
            {
                const int c = cid(i, j, k, m.nx, m.ny);
                const double x0 = cfg.Lx * i / m.nx;
                const double x1 = cfg.Lx * (i + 1) / m.nx;
                const double y0 = ynode[j];
                const double y1 = ynode[j + 1];
                const double z0 = cfg.Lz * k / m.nz;
                const double z1 = cfg.Lz * (k + 1) / m.nz;
                const double dx = x1 - x0;
                const double dy = y1 - y0;
                const double dz = z1 - z0;
                m.xc[c] = 0.5 * (x0 + x1);
                m.yc[c] = 0.5 * (y0 + y1);
                m.zc[c] = 0.5 * (z0 + z1);
                m.volume[c] = dx * dy * dz;

                const double face_area[kFaces] = {dy * dz, dy * dz, dx * dz,
                                                  dx * dz, dx * dy, dx * dy};
                const int ni[kFaces][3] = {{i - 1, j, k}, {i + 1, j, k}, {i, j - 1, k},
                                           {i, j + 1, k}, {i, j, k - 1}, {i, j, k + 1}};
                for (int f = 0; f < kFaces; ++f)
                {
                    m.area[c * kFaces + f] = face_area[f];
                    m.nxyz[(c * kFaces + f) * 3 + 0] = nrm[f][0];
                    m.nxyz[(c * kFaces + f) * 3 + 1] = nrm[f][1];
                    m.nxyz[(c * kFaces + f) * 3 + 2] = nrm[f][2];
                    const int ii = ni[f][0], jj = ni[f][1], kk = ni[f][2];
                    if (ii >= 0 && ii < m.nx && jj >= 0 && jj < m.ny && kk >= 0 && kk < m.nz)
                        m.neigh[c * kFaces + f] = cid(ii, jj, kk, m.nx, m.ny);
                    else
                    {
                        m.wall_face[c * kFaces + f] = 1;
                        int bc = bc_face[f];
                        /* Incident shock generator: post-shock RH on ymax for x >= Shock_X_Top. */
                        if (f == 3 && m.xc[c] >= cfg.shock_x_top)
                            bc = BC_POSTSHOCK;
                        m.bc_type[c * kFaces + f] = bc;
                    }
                }
            }

    return m;
}

} // namespace euler3d
