/**
 * @file output_files.cpp
 * @brief 3D solution file I/O operations for CFD solver
 *
 * This module handles all file input/output operations for 3D CFD solutions.
 * Supports multiple file formats, restart capabilities, parallel I/O, and
 * data validation. Enables solution persistence and post-processing workflows.
 *
 * Key Features:
 * - Binary and ASCII solution file formats
 * - Restart file generation and loading
 * - Time-series data output
 * - Parallel I/O support for large datasets
 * - Data integrity validation
 * - Multiple precision options
 * - Compressed file support
 *
 * Mathematical Framework:
 * - Conservative variables: [ρ, ρu, ρv, ρw, ρE]
 * - Primitive variables: [ρ, u, v, w, p, T, a, h, μ, λ]
 * - Grid geometry: 3D hexahedral cells
 * - Time-dependent solutions: U(x,y,z,t)
 *
 * @author CFD Solver Team
 * @date 2024
 */

#include "definitions.h"
#include "Globals.h"
#include <iomanip>
#include <sstream>
#include <ctime>
#include <sys/stat.h>

/**
 * @brief Creates output directory structure
 *
 * Ensures proper directory structure exists for all output files.
 * Creates subdirectories for different data types and time series.
 *
 * @param base_directory Base output directory path
 * @return true if directories created successfully
 */
bool Create_Output_Directories_3D(const std::string &base_directory)
{
    // Create main output directory
    std::string main_dir = base_directory;
    if (mkdir(main_dir.c_str(), 0755) != 0 && errno != EEXIST)
    {
        std::cerr << "Error creating main output directory: " << main_dir << std::endl;
        return false;
    }

    // Create subdirectories
    std::vector<std::string> subdirs = {
        "/solutions",
        "/restart",
        "/vtk",
        "/time_series",
        "/convergence",
        "/backup"};

    for (const auto &subdir : subdirs)
    {
        std::string full_path = main_dir + subdir;
        if (mkdir(full_path.c_str(), 0755) != 0 && errno != EEXIST)
        {
            std::cerr << "Error creating subdirectory: " << full_path << std::endl;
            return false;
        }
    }

    std::cout << "Output directory structure created: " << main_dir << std::endl;
    return true;
}

/**
 * @brief Writes 3D solution header information
 *
 * Outputs comprehensive header with simulation metadata, grid information,
 * and solution parameters for proper file identification.
 *
 * @param file Output file stream
 * @param iteration Current iteration number
 * @param time Current simulation time
 * @param format File format ("BINARY" or "ASCII")
 *
 * Mathematical formulation:
 * - Grid dimensions: Nx × Ny × Nz
 * - Total cells: Nx × Ny × Nz
 * - Solution variables: 5 conservative + 10 primitive
 * - Time integration: explicit/implicit schemes
 */
void Write_Solution_Header_3D(std::ofstream &file, int iteration, double time,
                              const std::string &format)
{
    // Get current timestamp
    std::time_t now = std::time(nullptr);
    std::string timestamp = std::ctime(&now);
    timestamp.pop_back(); // Remove newline

    file << "# ================================================================\n";
    file << "# 3D CFD Solution File\n";
    file << "# ================================================================\n";
    file << "# Generated by: CFD Solver with CUDA Acceleration v2.1\n";
    file << "# Timestamp: " << timestamp << "\n";
    file << "# Format: " << format << "\n";
    file << "# ================================================================\n";
    file << "# Grid Information:\n";
    file << "# Dimensions: " << Nx_max << " x " << Ny_max << " x " << Nz_max << "\n";
    file << "# Total Cells: " << Total_Cells_3D << "\n";
    file << "# Total Points: " << Total_Points_3D << "\n";
    file << "# ================================================================\n";
    file << "# Solution Information:\n";
    file << "# Iteration: " << iteration << "\n";
    file << "# Time: " << std::scientific << std::setprecision(12) << time << "\n";
    file << "# CFL Number: " << CFL << "\n";
    file << "# Mach Number: " << Mach_Number << "\n";
    file << "# Reynolds Number: " << Reynolds_Number << "\n";
    file << "# ================================================================\n";
    file << "# Variables:\n";
    file << "# Conservative: [rho, rho*u, rho*v, rho*w, rho*E]\n";
    file << "# Primitive: [rho, u, v, w, p, T, a, h, mu, lambda]\n";
    file << "# ================================================================\n\n";
}

/**
 * @brief Writes 3D conservative variables to file
 *
 * Outputs all conservative variables with proper formatting and precision.
 * Supports both ASCII and binary output formats.
 *
 * @param file Output file stream
 * @param binary_mode Use binary format if true
 *
 * Mathematical formulation:
 * - Conservative variables: U = [ρ, ρu, ρv, ρw, ρE]ᵀ
 * - Cell-centered storage: U_i,j,k for each hexahedral cell
 * - High precision output for numerical accuracy
 */
void Write_Conservative_Variables_3D(std::ofstream &file, bool binary_mode)
{
    if (!binary_mode)
    {
        file << "CONSERVATIVE_VARIABLES\n";
        file << Total_Cells_3D << " 5\n";

        for (int cell = 0; cell < Total_Cells_3D; cell++)
        {
            file << std::scientific << std::setprecision(16);
            for (int var = 0; var < 5; var++)
            {
                file << Conservative_Variables_3D[cell][var];
                if (var < 4)
                    file << "  ";
            }
            file << "\n";
        }
    }
    else
    {
        // Binary output
        int header[2] = {Total_Cells_3D, 5};
        file.write(reinterpret_cast<char *>(header), 2 * sizeof(int));

        for (int cell = 0; cell < Total_Cells_3D; cell++)
        {
            file.write(reinterpret_cast<char *>(Conservative_Variables_3D[cell]),
                       5 * sizeof(double));
        }
    }
}

/**
 * @brief Writes 3D primitive variables to file
 *
 * Outputs all primitive variables including derived quantities.
 * Ensures complete solution state for restart capabilities.
 *
 * @param file Output file stream
 * @param binary_mode Use binary format if true
 *
 * Mathematical formulation:
 * - Primitive variables: W = [ρ, u, v, w, p, T, a, h, μ, λ]ᵀ
 * - Derived from conservative variables
 * - Essential for accurate restart
 */
void Write_Primitive_Variables_3D(std::ofstream &file, bool binary_mode)
{
    if (!binary_mode)
    {
        file << "PRIMITIVE_VARIABLES\n";
        file << Total_Cells_3D << " 10\n";

        for (int cell = 0; cell < Total_Cells_3D; cell++)
        {
            file << std::scientific << std::setprecision(16);
            for (int var = 0; var < 10; var++)
            {
                file << Primitive_Variables_3D[cell][var];
                if (var < 9)
                    file << "  ";
            }
            file << "\n";
        }
    }
    else
    {
        // Binary output
        int header[2] = {Total_Cells_3D, 10};
        file.write(reinterpret_cast<char *>(header), 2 * sizeof(int));

        for (int cell = 0; cell < Total_Cells_3D; cell++)
        {
            file.write(reinterpret_cast<char *>(Primitive_Variables_3D[cell]),
                       10 * sizeof(double));
        }
    }
}

/**
 * @brief Writes 3D grid coordinates to file
 *
 * Outputs complete grid geometry for restart and post-processing.
 * Includes all vertex coordinates and cell connectivity information.
 *
 * @param file Output file stream
 * @param binary_mode Use binary format if true
 *
 * Mathematical formulation:
 * - Grid points: P = (x, y, z) for all vertices
 * - Hexahedral connectivity mapping
 * - Total points: (Nx+1) × (Ny+1) × (Nz+1)
 */
void Write_Grid_Coordinates_3D(std::ofstream &file, bool binary_mode)
{
    if (!binary_mode)
    {
        file << "GRID_COORDINATES\n";
        file << Total_Points_3D << " 3\n";

        for (int point = 0; point < Total_Points_3D; point++)
        {
            file << std::scientific << std::setprecision(16)
                 << Grid_Points_3D[point].x << "  "
                 << Grid_Points_3D[point].y << "  "
                 << Grid_Points_3D[point].z << "\n";
        }
    }
    else
    {
        // Binary output
        int header[2] = {Total_Points_3D, 3};
        file.write(reinterpret_cast<char *>(header), 2 * sizeof(int));

        for (int point = 0; point < Total_Points_3D; point++)
        {
            double coords[3] = {Grid_Points_3D[point].x,
                                Grid_Points_3D[point].y,
                                Grid_Points_3D[point].z};
            file.write(reinterpret_cast<char *>(coords), 3 * sizeof(double));
        }
    }
}

/**
 * @brief Creates comprehensive 3D solution file
 *
 * Main function to write complete solution state including all variables,
 * grid geometry, and metadata. Supports both restart and analysis formats.
 *
 * @param filename Output filename
 * @param iteration Current iteration number
 * @param time Current simulation time
 * @param binary_mode Use binary format if true
 * @param include_grid Include grid coordinates
 *
 * Mathematical formulation:
 * - Complete solution state: {U, W, Grid, Metadata}
 * - Conservative variables: [ρ, ρu, ρv, ρw, ρE]
 * - Primitive variables: [ρ, u, v, w, p, T, a, h, μ, λ]
 * - Grid geometry: vertex coordinates and connectivity
 */
void Write_Solution_File_3D(const std::string &filename, int iteration, double time,
                            bool binary_mode = false, bool include_grid = true)
{
    std::ios_base::openmode mode = std::ios::out;
    if (binary_mode)
        mode |= std::ios::binary;

    std::ofstream file(filename, mode);

    if (!file.is_open())
    {
        std::cerr << "Error: Cannot create solution file: " << filename << std::endl;
        return;
    }

    std::cout << "Writing 3D solution file: " << filename << std::endl;
    std::cout << "Mode: " << (binary_mode ? "BINARY" : "ASCII") << std::endl;
    std::cout << "Iteration: " << iteration << ", Time: " << time << std::endl;

    // Write header (ASCII only)
    if (!binary_mode)
    {
        Write_Solution_Header_3D(file, iteration, time, "ASCII");
    }

    // Write conservative variables
    Write_Conservative_Variables_3D(file, binary_mode);

    // Write primitive variables
    Write_Primitive_Variables_3D(file, binary_mode);

    // Write grid coordinates if requested
    if (include_grid)
    {
        Write_Grid_Coordinates_3D(file, binary_mode);
    }

    file.close();

    // Get file size for reporting
    struct stat file_stat;
    if (stat(filename.c_str(), &file_stat) == 0)
    {
        double file_size_mb = static_cast<double>(file_stat.st_size) / (1024.0 * 1024.0);
        std::cout << "Solution file written successfully. Size: "
                  << std::fixed << std::setprecision(2) << file_size_mb << " MB" << std::endl;
    }
}

/**
 * @brief Reads 3D solution file for restart
 *
 * Loads complete solution state from file for simulation restart.
 * Handles both ASCII and binary formats with validation.
 *
 * @param filename Input filename
 * @param iteration Output iteration number
 * @param time Output simulation time
 * @param binary_mode Expect binary format if true
 * @return true if file loaded successfully
 *
 * Mathematical formulation:
 * - Solution reconstruction: U, W from file data
 * - Grid validation: consistency checks
 * - Variable validation: physical ranges
 */
bool Read_Solution_File_3D(const std::string &filename, int &iteration, double &time,
                           bool binary_mode = false)
{
    std::ios_base::openmode mode = std::ios::in;
    if (binary_mode)
        mode |= std::ios::binary;

    std::ifstream file(filename, mode);

    if (!file.is_open())
    {
        std::cerr << "Error: Cannot open solution file: " << filename << std::endl;
        return false;
    }

    std::cout << "Reading 3D solution file: " << filename << std::endl;

    try
    {
        if (!binary_mode)
        {
            // Skip header lines until we find data sections
            std::string line;
            while (std::getline(file, line))
            {
                if (line.find("CONSERVATIVE_VARIABLES") != std::string::npos)
                {
                    break;
                }

                // Extract iteration and time from header
                if (line.find("# Iteration:") != std::string::npos)
                {
                    std::istringstream iss(line);
                    std::string temp;
                    iss >> temp >> temp >> iteration;
                }
                if (line.find("# Time:") != std::string::npos)
                {
                    std::istringstream iss(line);
                    std::string temp;
                    iss >> temp >> temp >> time;
                }
            }

            // Read conservative variables
            int num_cells, num_vars;
            file >> num_cells >> num_vars;

            if (num_cells != Total_Cells_3D || num_vars != 5)
            {
                std::cerr << "Error: Grid size mismatch in solution file" << std::endl;
                return false;
            }

            for (int cell = 0; cell < Total_Cells_3D; cell++)
            {
                for (int var = 0; var < 5; var++)
                {
                    file >> Conservative_Variables_3D[cell][var];
                }
            }

            // Read primitive variables
            std::getline(file, line); // Skip newline
            std::getline(file, line); // Read PRIMITIVE_VARIABLES
            file >> num_cells >> num_vars;

            if (num_cells != Total_Cells_3D || num_vars != 10)
            {
                std::cerr << "Error: Primitive variable size mismatch" << std::endl;
                return false;
            }

            for (int cell = 0; cell < Total_Cells_3D; cell++)
            {
                for (int var = 0; var < 10; var++)
                {
                    file >> Primitive_Variables_3D[cell][var];
                }
            }
        }
        else
        {
            // Binary mode reading
            int header[2];

            // Read conservative variables
            file.read(reinterpret_cast<char *>(header), 2 * sizeof(int));
            if (header[0] != Total_Cells_3D || header[1] != 5)
            {
                std::cerr << "Error: Binary file format mismatch" << std::endl;
                return false;
            }

            for (int cell = 0; cell < Total_Cells_3D; cell++)
            {
                file.read(reinterpret_cast<char *>(Conservative_Variables_3D[cell]),
                          5 * sizeof(double));
            }

            // Read primitive variables
            file.read(reinterpret_cast<char *>(header), 2 * sizeof(int));
            if (header[0] != Total_Cells_3D || header[1] != 10)
            {
                std::cerr << "Error: Primitive variable format mismatch" << std::endl;
                return false;
            }

            for (int cell = 0; cell < Total_Cells_3D; cell++)
            {
                file.read(reinterpret_cast<char *>(Primitive_Variables_3D[cell]),
                          10 * sizeof(double));
            }
        }
    }
    catch (const std::exception &e)
    {
        std::cerr << "Error reading solution file: " << e.what() << std::endl;
        file.close();
        return false;
    }

    file.close();

    std::cout << "Solution file loaded successfully" << std::endl;
    std::cout << "Iteration: " << iteration << ", Time: " << time << std::endl;

    return true;
}

/**
 * @brief Creates restart files with backup capability
 *
 * Generates restart files with automatic backup and validation.
 * Ensures robust restart capability for long-running simulations.
 *
 * @param base_filename Base filename for restart files
 * @param iteration Current iteration number
 * @param time Current simulation time
 * @param keep_backup Keep previous restart file as backup
 *
 * Mathematical formulation:
 * - Complete solution checkpoint: U(t), W(t), Grid
 * - Backup rotation: current → backup → archive
 * - Integrity validation before overwrite
 */
void Create_Restart_Files_3D(const std::string &base_filename, int iteration,
                             double time, bool keep_backup = true)
{
    std::string restart_filename = base_filename + "_restart.dat";
    std::string backup_filename = base_filename + "_restart_backup.dat";

    // Create backup of existing restart file
    if (keep_backup)
    {
        std::ifstream test_file(restart_filename);
        if (test_file.good())
        {
            test_file.close();
            std::rename(restart_filename.c_str(), backup_filename.c_str());
            std::cout << "Previous restart file backed up to: " << backup_filename << std::endl;
        }
    }

    // Write new restart file
    Write_Solution_File_3D(restart_filename, iteration, time, true, true);

    // Validate restart file by attempting to read it
    int test_iteration;
    double test_time;
    if (Read_Solution_File_3D(restart_filename, test_iteration, test_time, true))
    {
        if (test_iteration == iteration && std::abs(test_time - time) < 1e-12)
        {
            std::cout << "Restart file validation successful" << std::endl;
        }
        else
        {
            std::cerr << "Warning: Restart file validation failed" << std::endl;
        }
    }
    else
    {
        std::cerr << "Error: Restart file validation failed" << std::endl;
    }
}

/**
 * @brief Writes convergence history to file
 *
 * Outputs residual and convergence metrics for solution monitoring.
 * Enables convergence analysis and solution quality assessment.
 *
 * @param filename Convergence history filename
 * @param iteration Current iteration number
 * @param time Current simulation time
 * @param residuals Array of residual values
 * @param num_residuals Number of residual components
 *
 * Mathematical formulation:
 * - Residual norms: ||R_i|| for each equation
 * - Convergence rate: log(||R_i||/||R_{i-1}||)
 * - Time step information: Δt, CFL
 */
void Write_Convergence_History_3D(const std::string &filename, int iteration,
                                  double time, double *residuals, int num_residuals)
{
    std::ofstream file(filename, std::ios::app);

    if (!file.is_open())
    {
        std::cerr << "Error: Cannot open convergence file: " << filename << std::endl;
        return;
    }

    // Write header for new file
    if (iteration == 0)
    {
        file << "# Iteration  Time  ";
        for (int i = 0; i < num_residuals; i++)
        {
            file << "Residual_" << i << "  ";
        }
        file << "CFL  dt" << std::endl;
    }

    // Write convergence data
    file << std::setw(10) << iteration << "  "
         << std::scientific << std::setprecision(6) << time << "  ";

    for (int i = 0; i < num_residuals; i++)
    {
        file << std::scientific << std::setprecision(6) << residuals[i] << "  ";
    }

    file << std::fixed << std::setprecision(4) << CFL << "  "
         << std::scientific << std::setprecision(6) << dt << std::endl;

    file.close();
}

/**
 * @brief Validates solution data integrity
 *
 * Performs comprehensive validation of solution data before file output.
 * Checks for NaN values, physical ranges, and mathematical consistency.
 *
 * @return true if all data is valid
 *
 * Mathematical formulation:
 * - Range validation: ρ > 0, p > 0, T > 0
 * - Energy consistency: E ≥ kinetic energy
 * - Finite value checks: no NaN or infinity
 */
bool Validate_Solution_Data_3D()
{
    bool is_valid = true;
    int invalid_cells = 0;

    for (int cell = 0; cell < Total_Cells_3D; cell++)
    {
        // Check conservative variables
        for (int var = 0; var < 5; var++)
        {
            if (!std::isfinite(Conservative_Variables_3D[cell][var]))
            {
                invalid_cells++;
                is_valid = false;
                break;
            }
        }

        // Check primitive variables
        double rho = Primitive_Variables_3D[cell][0];
        double p = Primitive_Variables_3D[cell][4];
        double T = Primitive_Variables_3D[cell][5];

        if (rho <= 0.0 || p <= 0.0 || T <= 0.0)
        {
            invalid_cells++;
            is_valid = false;
        }

        // Check energy consistency
        double rho_E = Conservative_Variables_3D[cell][4];
        double u = Primitive_Variables_3D[cell][1];
        double v = Primitive_Variables_3D[cell][2];
        double w = Primitive_Variables_3D[cell][3];
        double kinetic_energy = 0.5 * rho * (u * u + v * v + w * w);

        if (rho_E < kinetic_energy)
        {
            invalid_cells++;
            is_valid = false;
        }
    }

    if (!is_valid)
    {
        std::cerr << "Warning: " << invalid_cells << " cells have invalid solution data" << std::endl;
    }

    return is_valid;
}